// <auto-generated />
using System;
using AquaGas.Plan.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AquaGas.Plan.Infrastructure.Migrations
{
    [DbContext(typeof(PlanDbContext))]
    [Migration("20260523163616_InitialPlan")]
    partial class InitialPlan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AquaGas.Plan.Domain.Models.Billing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReceivedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Billings", (string)null);
                });

            modelBuilder.Entity("AquaGas.Plan.Domain.Models.ContractPenalty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CanceledBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InitiatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("PaidBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WaiveReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("WaivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WaivedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("ContractPenalties", (string)null);
                });

            modelBuilder.Entity("AquaGas.Plan.Domain.Models.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasCustomSchedule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Deliveries", (string)null);
                });

            modelBuilder.Entity("AquaGas.Plan.Domain.Models.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("BillingDay")
                        .HasColumnType("integer");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cycle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeliveryDay")
                        .HasColumnType("integer");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuspensionReason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("AquaGas.Plan.Domain.Models.PlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanItems", (string)null);
                });

            modelBuilder.Entity("AquaGas.Plan.Domain.Models.Billing", b =>
                {
                    b.HasOne("AquaGas.Plan.Domain.Models.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AquaGas.Shared.Domain.ValueObjects.Price", "Amount", b1 =>
                        {
                            b1.Property<Guid>("BillingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Amount");

                            b1.HasKey("BillingId");

                            b1.ToTable("Billings");

                            b1.WithOwner()
                                .HasForeignKey("BillingId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("AquaGas.Plan.Domain.Models.ContractPenalty", b =>
                {
                    b.HasOne("AquaGas.Plan.Domain.Models.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AquaGas.Shared.Domain.ValueObjects.Price", "CalculatedAmount", b1 =>
                        {
                            b1.Property<Guid>("ContractPenaltyId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("CalculatedAmount");

                            b1.HasKey("ContractPenaltyId");

                            b1.ToTable("ContractPenalties");

                            b1.WithOwner()
                                .HasForeignKey("ContractPenaltyId");
                        });

                    b.OwnsOne("AquaGas.Shared.Domain.ValueObjects.Price", "OriginalValue", b1 =>
                        {
                            b1.Property<Guid>("ContractPenaltyId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("OriginalValue");

                            b1.HasKey("ContractPenaltyId");

                            b1.ToTable("ContractPenalties");

                            b1.WithOwner()
                                .HasForeignKey("ContractPenaltyId");
                        });

                    b.OwnsOne("AquaGas.Shared.Domain.ValueObjects.Price", "RemainingValue", b1 =>
                        {
                            b1.Property<Guid>("ContractPenaltyId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("RemainingValue");

                            b1.HasKey("ContractPenaltyId");

                            b1.ToTable("ContractPenalties");

                            b1.WithOwner()
                                .HasForeignKey("ContractPenaltyId");
                        });

                    b.Navigation("CalculatedAmount")
                        .IsRequired();

                    b.Navigation("OriginalValue")
                        .IsRequired();

                    b.Navigation("RemainingValue")
                        .IsRequired();
                });

            modelBuilder.Entity("AquaGas.Plan.Domain.Models.Delivery", b =>
                {
                    b.HasOne("AquaGas.Plan.Domain.Models.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AquaGas.Plan.Domain.Models.Plan", b =>
                {
                    b.OwnsOne("AquaGas.Shared.Domain.ValueObjects.Price", "Total", b1 =>
                        {
                            b1.Property<Guid>("PlanId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Total");

                            b1.HasKey("PlanId");

                            b1.ToTable("Plans");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.OwnsOne("AquaGas.Shared.Domain.ValueObjects.Discount", "CurrentDiscount", b1 =>
                        {
                            b1.Property<Guid>("PlanId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Value")
                                .HasPrecision(5, 2)
                                .HasColumnType("double precision")
                                .HasColumnName("CurrentDiscount");

                            b1.HasKey("PlanId");

                            b1.ToTable("Plans");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.Navigation("CurrentDiscount");

                    b.Navigation("Total")
                        .IsRequired();
                });

            modelBuilder.Entity("AquaGas.Plan.Domain.Models.PlanItem", b =>
                {
                    b.HasOne("AquaGas.Plan.Domain.Models.Plan", null)
                        .WithMany("Items")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AquaGas.Shared.Domain.ValueObjects.StockQuantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("PlanItemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("Quantity");

                            b1.HasKey("PlanItemId");

                            b1.ToTable("PlanItems");

                            b1.WithOwner()
                                .HasForeignKey("PlanItemId");
                        });

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("AquaGas.Plan.Domain.Models.Plan", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
